pipeline{
    agent any
            
    stages{
        stage('instalar paquetes.'){
            steps{
                echo "Instalar Paquetes"
                sh "pip install tox"
                sh "python3 -m tox -c section-05-production-model-package/tox.ini -e test_package"
                sh "python3 -m tox -c section-05-production-model-package/tox.ini -e train"
            }
        }
        
        stage('Paquete de Apis.'){
            steps{
                echo "running text on Section-05 Model Package"
                sh "pip install -r section-06-model-serving-api/house-prices-api/requirements.txt"
                sh "python3 -m tox -c section-06-model-serving-api/house-prices-api/tox.ini -e test_app"
            }
        }

        stage('Copiar a Produccion'){
            steps{
                sh "git push origin master"
            }
        }
    }
}
