pipeline{
    agent any
    
    stages{
        stage('Checkout...'){
            steps{
                echo "Checkout code..."
            }
        }
        
        stage('Hello'){
            steps{                
                sh "python3 section-08-deploying-with-containers/hello.py"                
            }
        }
        
        stage('TOX-Train model..'){
            steps{
                echo "running text on Section-05 Model Package"
                sh " python3 section-05-production-model-package/regression_model/train_pipeline.py"

            }
        }

        stage('Deploying to prod'){
            steps{
                echo "Deploying to prod env..."
            }
        }
    }
}
