pipeline{
    agent any
    
    stages{
        stage('Checkout...'){
            steps{
                echo "Checkout code..."
            }
        }
        
        stage('Hello'){
            steps{                
                sh "pip install tox"                
            }
        }
        
        stage('TOX-Train model..'){
            steps{
                echo "running text on Section-05 Model Package"
                sh "python3 -m tox -c section-05-production-model-package/tox.ini -e test_package"

            }
        }

        stage('Deploying to prod'){
            steps{
                sh "pip install uvicorn"
                sh " uvicorn section-06-model-serving-api\house-prices-api\app.main:app --reload"
            }
        }
    }
}
